name: "Build"
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:

  backend:
    name: "Backend"
    runs-on: "ubuntu-latest"
    container:
      image: "gradle"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2"
      - name: "Start Gradle Daemon"
        run: "gradle clean"
      - name: "Compile Project"
        run: "gradle assemble"
      - name: "Test Project"
        run: "gradle build"

  frontend:
    name: "Frontend"
    runs-on: "ubuntu-latest"
    container:
      image: "node:10"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2"
      - name: "Fetch Dependencies"
        working-directory: "./frontend"
        run: "yarn"
      - name: "Validate Project"
        working-directory: "./frontend"
        run: "yarn run check"
      - name: "Build Project"
        working-directory: "./frontend"
        run: "yarn run build"
      - name: "Upload Static Site"
        uses: "actions/upload-artifact@v2"
        with:
          name: "static-site"
          path: "frontend/public/"

  bundle:
    name: "Bundle Application"
    runs-on: "ubuntu-latest"
    container:
      image: "gradle"
    needs: ["backend", "frontend"]
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2"
      - name: "Clear Frontend"
        run: "rm -rf frontend/public"
      - name: "Bundle Frontend"
        uses: "actions/download-artifact@v4.1.7"
        with:
          name: "static-site"
          path: "frontend/public/"
      - name: "Start Gradle Daemon"
        run: "gradle clean"
      - name: "Bundle Project"
        run: "gradle shadowJar"
      - name: "Upload Bundled Application"
        uses: "actions/upload-artifact@v2"
        with:
          name: "pancake-bundled"
          path: "application/build/libs/application-*-all.jar"
