name: "Build"
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:

  backend:
    name: "Backend"
    runs-on: "ubuntu-latest"
    container:
      image: "gradle"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2"
      - name: "Start Gradle Daemon"
        run: "gradle clean"
      - name: "Compile Project"
        run: "gradle assemble"
      - name: "Test Project"
        run: "gradle build"
